---
- name: generate metrics-server certificates
  include_tasks: setup_certificate.yaml
  vars:
    component: metrics-server
    hostnames: "metrics-server,metrics-server.{{ openshift_metrics_metrics_server_project }}.svc.cluster.local,{{ openshift_metrics_metrics_server_hostname }}"
  changed_when: no

- name: read files for the metrics-server secret
  shell: >
    printf '%s: ' '{{ item }}'
    && base64 --wrap 0 '{{ mktemp.stdout }}/{{ item }}'
  register: metrics_metrics_server_secrets
  with_items:
  - ca.crt
  - metrics-server.crt
  - metrics-server.key
  - metrics-server.pem
  changed_when: false

- set_fact:
    metrics_metrics_server_secrets: |
      {{ metrics_metrics_server_secrets.results|map(attribute='stdout')|join('
      ')|from_yaml }}

- slurp:
    src: "{{ mktemp.stdout }}/ca.crt"
  register: apiserver_ca

- name: generate metrics-server-certs secret template
  template:
    src: secret.j2
    dest: "{{ mktemp.stdout }}/templates/metrics-server-certs.yaml"
  vars:
    name: metrics-server-certs
    labels:
      metrics-infra: metrics-server-certs
    annotations:
      service.alpha.openshift.io/originating-service-name: metrics-server
    data:
      tls.crt: >
        {{ metrics_metrics_server_secrets['metrics-server.crt'] }}
      tls.key: >
        {{ metrics_metrics_server_secrets['metrics-server.key'] }}
      ca.crt: >
        {{ metrics_metrics_server_secrets['ca.crt'] }}
  when: name not in metrics_server_secrets.stdout_lines
  changed_when: no

- name: Generate metrics-server apiservice
  template:
    src: metrics-server-apiservice.j2
    dest: "{{ mktemp.stdout }}/templates/{{ obj_name }}-apiservice.yaml"
  vars:
    obj_name: metrics-server
    namespace: "{{ openshift_metrics_metrics_server_project }}"
    caBundle: "{{ apiserver_ca.content }}"
  changed_when: no
