- slurp:
    src: "{{ mktemp.stdout }}/ca.crt"
  register: apiserver_ca

- name: Generate metrics-server apiservice
  template:
    src: metrics-server-apiservice.j2
    dest: "{{ mktemp.stdout }}/templates/{{ obj_name }}-apiservice.yaml"
  vars:
    obj_name: metrics-server
    namespace: "{{ openshift_metrics_metrics_server_project }}"
    caBundle: "{{ apiserver_ca.content }}"
  changed_when: no
